project:
  type: website
  output-dir: _site

website:
  title: "The Security Isolation Imperative"
  description: "An educational project exploring the shift to architectural isolation with Edera, Kata Containers, gVisor, and the broader cloud-native ecosystem."
  favicon: assets/images/logo.svg
  navbar:
    logo: assets/images/logo.svg
    left:
      - text: "Posts"
        href: posts/index.qmd
      - text: "Compare"
        href: pages/isolation-vs-oss.qmd
      - text: "Community"
        href: pages/community.qmd
      - text: "About"
        href: pages/about.qmd
      - text: "Proposal"
        href: pages/proposal.qmd

  page-navigation: true
  search: true

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true
    toc-depth: 3
    number-sections: false
    code-tools: true
    code-fold: show
    include-after-body: partials/giscus-comments.html
